//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Performance.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V0,&quot;0.1.0&quot;
        ///T1,&quot;TransitionTime&quot;,&quot;IsFixedDateRule&quot;,&quot;Day&quot;,&quot;Month&quot;,&quot;TimeOfDay&quot;,&quot;Week&quot;,&quot;DayOfWeek&quot;
        ///T2,&quot;Adjustment&quot;,&quot;StartDate&quot;,&quot;EndDate&quot;,&quot;DaylightDeltaHours&quot;,&quot;TransitionStart&quot;,&quot;TransitionEnd&quot;
        ///T3,&quot;TimeZone&quot;,&quot;Id&quot;,&quot;DisplayName&quot;,&quot;DaylightName&quot;,&quot;StandardName&quot;,&quot;HasDst&quot;,&quot;UtcOffsetHours&quot;,&quot;Adjustments&quot;
        ///T4,&quot;TimeZones&quot;,&quot;AllTimeZones&quot;
        ///I5,#3,&quot;Dateline Standard Time&quot;,&quot;(UTC-12:00) International Date Line West&quot;,&quot;Dateline Daylight Time&quot;,&quot;Dateline Standard Time&quot;,F,-12,
        ///I6,#3,&quot;UTC-11&quot;,&quot;(UTC-11:00) Coordinated Universal Time-11&quot;,&quot;U [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tz_csn {
            get {
                return ResourceManager.GetString("tz_csn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;AllTimeZones&quot;:[{&quot;Id&quot;:&quot;Dateline Standard Time&quot;,&quot;DisplayName&quot;:&quot;(UTC-12:00) International Date Line West&quot;,&quot;DaylightName&quot;:&quot;Dateline Daylight Time&quot;,&quot;StandardName&quot;:&quot;Dateline Standard Time&quot;,&quot;HasDst&quot;:false,&quot;UtcOffsetHours&quot;:-12.0,&quot;Adjustments&quot;:[]},{&quot;Id&quot;:&quot;UTC-11&quot;,&quot;DisplayName&quot;:&quot;(UTC-11:00) Coordinated Universal Time-11&quot;,&quot;DaylightName&quot;:&quot;UTC-11&quot;,&quot;StandardName&quot;:&quot;UTC-11&quot;,&quot;HasDst&quot;:false,&quot;UtcOffsetHours&quot;:-11.0,&quot;Adjustments&quot;:[]},{&quot;Id&quot;:&quot;Aleutian Standard Time&quot;,&quot;DisplayName&quot;:&quot;(UTC-10:00) Aleutian Islands&quot;,&quot;DaylightName&quot;:&quot;Al [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tz_json_long {
            get {
                return ResourceManager.GetString("tz_json_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;A&quot;:[{&quot;B&quot;:&quot;Dateline Standard Time&quot;,&quot;C&quot;:&quot;(UTC-12:00) International Date Line West&quot;,&quot;D&quot;:&quot;Dateline Daylight Time&quot;,&quot;E&quot;:&quot;Dateline Standard Time&quot;,&quot;F&quot;:false,&quot;G&quot;:-12.0,&quot;H&quot;:[]},{&quot;B&quot;:&quot;UTC-11&quot;,&quot;C&quot;:&quot;(UTC-11:00) Coordinated Universal Time-11&quot;,&quot;D&quot;:&quot;UTC-11&quot;,&quot;E&quot;:&quot;UTC-11&quot;,&quot;F&quot;:false,&quot;G&quot;:-11.0,&quot;H&quot;:[]},{&quot;B&quot;:&quot;Aleutian Standard Time&quot;,&quot;C&quot;:&quot;(UTC-10:00) Aleutian Islands&quot;,&quot;D&quot;:&quot;Aleutian Daylight Time&quot;,&quot;E&quot;:&quot;Aleutian Standard Time&quot;,&quot;F&quot;:true,&quot;G&quot;:-10.0,&quot;H&quot;:[{&quot;I&quot;:&quot;0001-01-01T00:00:00&quot;,&quot;J&quot;:&quot;2006-12-31T00:00:00&quot;,&quot;K&quot;:1.0,&quot;L&quot;:{&quot;N&quot;:false,&quot;O&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tz_json_short {
            get {
                return ResourceManager.GetString("tz_json_short", resourceCulture);
            }
        }
    }
}
